apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: websocket-server
  name: websocket-server
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: websocket-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
        - image: jwfeb05/jw-home-websocket-server:latest
          imagePullPolicy: Always
          name: websocket-server
          ports:
            - containerPort: 9093
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: REDIS_PORT
            - name: REDIS_PASS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: REDIS_PASS
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: KAFKA_BROKERS
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: websocket-server
  name: websocket-server
  namespace: default
spec:
  ports:
    - port: 9093 #CHANGE
      protocol: TCP
      targetPort: 9093 #CHANGE
  selector:
    app: websocket-server
  sessionAffinity: None #CHANGE
  type: NodePort