server:
  port: 9093
spring:
  application:
    name: websocket-server
  redis:
    host: host
    port: 6379
    password: password
    pubsub:
      device:
        control-request-channel: websocket-control-request
        control-response-channel: websocket-control-response
  kafka:
    bootstrap-servers: broker:9092
    topics:
      device-state: ec2.jwhome.dev.device-state.json
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka